# RPC URL for Polygon Amoy (Alchemy or public endpoint)
RPC_URL = "https://polygon-amoy.g.alchemy.com/v2/YOUR_ALCHEMY_API_KEY"

# Private key for testing (⚠️ use a fresh test wallet with faucet MATIC only)
SHOP_PRIVATE_KEY = "0xYOUR_PRIVATE_KEY_HERE"

# Addresses of deployed contracts (you’ll copy these from Brownie deploy output)
SHOP_ADDRESS = "0x5623Bb6f7181cC069B86837960a1466eB3C5db02"
TOKEN_ADDRESS = "0x2BCBa6b84C24BdeC420A1d90F03cE305f7D11037"
NFT_ADDRESS   = "0xfcc42316b05A9296483A3C42DB8B15Fe73E66740"